### ISSUE TITLE
Failed to open TCP connection

### ISSUE THREAD

**Issue by noctivityinc** [amzn/login-and-pay-with-amazon-sdk-ruby#10]
I have the latest gem installed.  Unfortunately, all attempts to use it fail due to a TCP error.  Please advise.

```
@pay_by_amazon = PayWithAmazon::Client.new(
  APP_CONFIG[:amazon_seller_id],
  APP_CONFIG[:amazon_access_key_id],
  APP_CONFIG[:amazon_secret_key_id], 
  sandbox: Rails.env.test? || Rails.env.development?
)

oid = 'VALID ORDER ID RETURNED FROM EXPRESS INTEGRATION'

[2] pry(main)> @pay_by_amazon.get_order_reference_details(oid)
RuntimeError: Failed to open TCP connection to mws.amazonservices.com:443 (getaddrinfo: nodename nor servname provided, or not known)
from /Users/jlippiner/.rvm/gems/ruby-2.3.0@dmvcs/gems/pay_with_amazon-1.1.0/lib/pay_with_amazon/request.rb:95:in `rescue in post'

[3] pry(main)> @pay_by_amazon.confirm_order_reference(oid)
RuntimeError: Failed to open TCP connection to mws.amazonservices.com:443 (getaddrinfo: nodename nor servname provided, or not known)
from /Users/jlippiner/.rvm/gems/ruby-2.3.0@dmvcs/gems/pay_with_amazon-1.1.0/lib/pay_with_amazon/request.rb:95:in `rescue in post'
```

**Comment by tarishah** [comment]
Are you working under a corporate network? That sometimes might be blocking the connectivity.

**Comment by noctivityinc** [comment]
No.  Connecting from home computer.

**Comment by noctivityinc** [comment]
appears to have been a local issue.  Restarted and all good now.  thx
